name: Generate snake game

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12h
  workflow_dispatch:

permissions:
  contents: write            # necessário para publicar no branch "output"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: AllysonAugusto
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
